const API_BASE_URL = 'http://localhost:3000';

const TOP_100_PASSWORDS = [
    '123456', 'password', '123456789', '12345', '1234', '111111', '1234567', 'dragon',
    '123123', 'baseball', 'abc123', 'football', 'monkey', 'letmein', '696969', 'shadow',
    'master', '666666', 'qwertyuiop', '123321', 'mustang', '1234567890', 'amanda', 'summer',
    'love', 'ashley', 'bailey', 'passw0rd', 'shadow', '123123', '654321', 'superman',
    'qazwsx', 'michael', 'football', 'password1', 'password123', 'qwerty', '1111111',
    '12345678', '000000', '1qaz2wsx', '121212', 'sunshine', 'princess', 'iloveyou',
    '1q2w3e4r', 'batman', 'login', 'admin', 'welcome', 'hello', 'charlie', 'donald',
    'password12', '123qwe', 'november', 'xxxxxx', 'password1234', 'thx1138', 'asdfgh',
    'zxcvbnm', '123456a', '7777777', '1q2w3e', 'test', 'trustno1', 'master', 'cheese',
    '159753', 'arsenal', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
    '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
    '2019', '2020', '2021', '2022', '2023', '2024', 'qwerty123', 'letmein1', 'welcome1'
];

const NICKNAME_SUFFIXES = ['_', 'x', 'z', 'pro', 'official', 'real', 'the', 'mr', 'ms'];

const form = document.getElementById('registerForm');
const phoneInput = document.getElementById('phone');
const emailInput = document.getElementById('email');
const dateOfBirthInput = document.getElementById('dateOfBirth');
const passwordMethodRadios = document.getElementsByName('passwordMethod');
const passwordManualGroup = document.getElementById('passwordManualGroup');
const passwordAutoGroup = document.getElementById('passwordAutoGroup');
const passwordInput = document.getElementById('password');
const passwordRepeatInput = document.getElementById('passwordRepeat');
const autoPasswordInput = document.getElementById('autoPassword');
const regenerateBtn = document.getElementById('regenerateBtn');
const firstNameInput = document.getElementById('firstName');
const lastNameInput = document.getElementById('lastName');
const patronymicInput = document.getElementById('patronymic');
const nicknameInput = document.getElementById('nickname');
const generateNicknameBtn = document.getElementById('generateNicknameBtn');
const nicknameAttemptsEl = document.getElementById('nicknameAttempts');
const agreementCheckbox = document.getElementById('agreement');
const submitBtn = document.getElementById('submitBtn');

let nicknameAttempts = 0;
let autoGeneratedPassword = '';
let isPasswordMethodManual = true;

async function hashPassword(password) {
    const encoder = new TextEncoder();
    const data = encoder.encode(password);

    const hashBuffer = await crypto.subtle.digest('SHA-256', data);

    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

function formatPhoneBy(value) {
    let digits = value.replace(/\D/g, '');

    if (digits.startsWith('375')) {
        digits = digits.slice(0, 12);
    } else if (digits.startsWith('8')) {
        digits = '375' + digits.slice(1, 11);
    } else if (digits.length > 0 && !digits.startsWith('375')) {
        if (digits.length <= 2) {
            digits = '375' + digits;
        } else {
            digits = '375' + digits.slice(0, 9);
        }
    }

    let formattedValue = '';

    if (digits.length > 0) {
        formattedValue = '+' + digits.slice(0, 3);
    }
    if (digits.length > 3) {
        formattedValue += ' (' + digits.slice(3, 5);
        if (digits.length > 5) {
            formattedValue += ') ';
        }
    }
    if (digits.length > 5) {
        formattedValue += digits.slice(5, 8);
    }
    if (digits.length > 8) {
        formattedValue += '-' + digits.slice(8, 10);
    }
    if (digits.length > 10) {
        formattedValue += '-' + digits.slice(10, 12);
    }

    return formattedValue;
}

phoneInput.addEventListener('input', (e) => {
    const oldValue = e.target.value;
    const oldCursorPos = e.target.selectionStart;

    e.target.value = formatPhoneBy(e.target.value);

    const newValue = e.target.value;
    const diff = newValue.length - oldValue.length;

    if (oldCursorPos !== null && oldCursorPos !== undefined) {
        const newCursorPos = Math.min(oldCursorPos + diff, newValue.length);
        e.target.setSelectionRange(newCursorPos, newCursorPos);
    }

    validatePhone();
});

phoneInput.addEventListener('keydown', (e) => {
    if (e.key === 'Backspace' || e.key === 'Delete' ||
        e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
        return;
    }
});

function validatePhone() {
    const phone = phoneInput.value.replace(/\D/g, '');
    const errorEl = document.getElementById('phoneError');
    const successEl = document.getElementById('phoneSuccess');

    if (phone.length === 0) {
        errorEl.textContent = '';
        successEl.textContent = '';
        phoneInput.classList.remove('error', 'success');
        return false;
    }

    if (phone.length !== 12) {
        errorEl.textContent = `Номер телефона должен содержать 12 цифр (сейчас: ${phone.length}). Пример: +375291234567`;
        successEl.textContent = '';
        phoneInput.classList.add('error');
        phoneInput.classList.remove('success');
        return false;
    }

    if (!phone.startsWith('375')) {
        errorEl.textContent = 'Разрешена регистрация только на номера Республики Беларусь (+375)';
        successEl.textContent = '';
        phoneInput.classList.add('error');
        phoneInput.classList.remove('success');
        return false;
    }

    const operatorCode = phone.slice(3, 5);
    const validCodes = ['25', '29', '33', '44'];

    if (!validCodes.includes(operatorCode)) {
        errorEl.textContent = `Неверный код оператора (${operatorCode}). Допустимые коды: 25, 29, 33, 44`;
        successEl.textContent = '';
        phoneInput.classList.add('error');
        phoneInput.classList.remove('success');
        return false;
    }

    errorEl.textContent = '';
    successEl.textContent = '✓ Номер телефона корректен';
    phoneInput.classList.remove('error');
    phoneInput.classList.add('success');
    return true;
}

function validateEmail() {
    const email = emailInput.value.trim();
    const errorEl = document.getElementById('emailError');
    const successEl = document.getElementById('emailSuccess');
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    if (email.length === 0) {
        errorEl.textContent = '';
        successEl.textContent = '';
        emailInput.classList.remove('error', 'success');
        return false;
    }

    if (!emailRegex.test(email)) {
        errorEl.textContent = 'Введите корректный email адрес';
        successEl.textContent = '';
        emailInput.classList.add('error');
        emailInput.classList.remove('success');
        return false;
    }

    errorEl.textContent = '';
    successEl.textContent = '✓ Email корректен';
    emailInput.classList.remove('error');
    emailInput.classList.add('success');
    return true;
}

emailInput.addEventListener('input', validateEmail);

function validateDateOfBirth() {
    const dateOfBirth = dateOfBirthInput.value;
    const errorEl = document.getElementById('dateOfBirthError');
    const successEl = document.getElementById('dateOfBirthSuccess');

    if (!dateOfBirth) {
        errorEl.textContent = '';
        successEl.textContent = '';
        dateOfBirthInput.classList.remove('error', 'success');
        return false;
    }

    const birthDate = new Date(dateOfBirth);
    const today = new Date();
    const age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();

    let actualAge = age;
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
        actualAge--;
    }

    if (actualAge < 16) {
        errorEl.textContent = `Вам должно исполниться 16 лет. Сейчас вам ${actualAge} лет.`;
        successEl.textContent = '';
        dateOfBirthInput.classList.add('error');
        dateOfBirthInput.classList.remove('success');
        return false;
    }

    errorEl.textContent = '';
    successEl.textContent = '✓ Возраст соответствует требованиям';
    dateOfBirthInput.classList.remove('error');
    dateOfBirthInput.classList.add('success');
    return true;
}

dateOfBirthInput.addEventListener('change', validateDateOfBirth);

passwordMethodRadios.forEach(radio => {
    radio.addEventListener('change', (e) => {
        isPasswordMethodManual = e.target.value === 'manual';

        if (isPasswordMethodManual) {
            passwordManualGroup.style.display = 'block';
            passwordAutoGroup.style.display = 'none';
            passwordInput.required = true;
            passwordRepeatInput.required = true;
        } else {
            passwordManualGroup.style.display = 'none';
            passwordAutoGroup.style.display = 'block';
            passwordInput.required = false;
            passwordRepeatInput.required = false;
            generateAutoPassword();
        }

        validateForm();
    });
});

function generateSecurePassword() {
    const uppercase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const lowercase = 'abcdefghijklmnopqrstuvwxyz';
    const numbers = '0123456789';
    const special = '!@#$%^&*()_+-=[]{}|;:,.<>?';

    let password = '';
    password += uppercase[Math.floor(Math.random() * uppercase.length)];
    password += lowercase[Math.floor(Math.random() * lowercase.length)];
    password += numbers[Math.floor(Math.random() * numbers.length)];
    password += special[Math.floor(Math.random() * special.length)];

    const allChars = uppercase + lowercase + numbers + special;
    const remainingLength = Math.floor(Math.random() * 13) + 8; // 8-20 символов

    for (let i = 0; i < remainingLength - 4; i++) {
        password += allChars[Math.floor(Math.random() * allChars.length)];
    }

    return password.split('').sort(() => Math.random() - 0.5).join('');
}

function generateAutoPassword() {
    let newPassword;
    let attempts = 0;

    do {
        newPassword = generateSecurePassword();
        attempts++;
    } while (TOP_100_PASSWORDS.includes(newPassword.toLowerCase()) && attempts < 100);

    autoGeneratedPassword = newPassword;
    autoPasswordInput.value = newPassword;
}

regenerateBtn.addEventListener('click', generateAutoPassword);

function validatePassword() {
    if (!isPasswordMethodManual) return true;

    const password = passwordInput.value;
    const errorEl = document.getElementById('passwordError');
    const successEl = document.getElementById('passwordSuccess');

    updatePasswordRequirements(password);

    if (password.length === 0) {
        errorEl.textContent = '';
        successEl.textContent = '';
        passwordInput.classList.remove('error', 'success');
        return false;
    }

    if (password.length < 8 || password.length > 20) {
        errorEl.textContent = 'Пароль должен содержать от 8 до 20 символов';
        successEl.textContent = '';
        passwordInput.classList.add('error');
        passwordInput.classList.remove('success');
        return false;
    }

    if (!/[A-Z]/.test(password)) {
        errorEl.textContent = 'Пароль должен содержать хотя бы одну заглавную букву';
        successEl.textContent = '';
        passwordInput.classList.add('error');
        passwordInput.classList.remove('success');
        return false;
    }

    if (!/[a-z]/.test(password)) {
        errorEl.textContent = 'Пароль должен содержать хотя бы одну строчную букву';
        successEl.textContent = '';
        passwordInput.classList.add('error');
        passwordInput.classList.remove('success');
        return false;
    }

    if (!/[0-9]/.test(password)) {
        errorEl.textContent = 'Пароль должен содержать хотя бы одну цифру';
        successEl.textContent = '';
        passwordInput.classList.add('error');
        passwordInput.classList.remove('success');
        return false;
    }

    if (!/[!@#$%^&*()_+\-=\[\]{}|;:,.<>?]/.test(password)) {
        errorEl.textContent = 'Пароль должен содержать хотя бы один специальный символ';
        successEl.textContent = '';
        passwordInput.classList.add('error');
        passwordInput.classList.remove('success');
        return false;
    }

    if (TOP_100_PASSWORDS.includes(password.toLowerCase())) {
        errorEl.textContent = 'Этот пароль слишком распространён. Выберите другой.';
        successEl.textContent = '';
        passwordInput.classList.add('error');
        passwordInput.classList.remove('success');
        return false;
    }

    errorEl.textContent = '';
    successEl.textContent = '✓ Пароль соответствует требованиям';
    passwordInput.classList.remove('error');
    passwordInput.classList.add('success');
    return true;
}

function updatePasswordRequirements(password) {
    document.getElementById('req-length').className = 'req-item ' + (password.length >= 8 && password.length <= 20 ? 'valid' : 'invalid');
    document.getElementById('req-uppercase').className = 'req-item ' + (/[A-Z]/.test(password) ? 'valid' : 'invalid');
    document.getElementById('req-lowercase').className = 'req-item ' + (/[a-z]/.test(password) ? 'valid' : 'invalid');
    document.getElementById('req-number').className = 'req-item ' + (/[0-9]/.test(password) ? 'valid' : 'invalid');
    document.getElementById('req-special').className = 'req-item ' + (/[!@#$%^&*()_+\-=\[\]{}|;:,.<>?]/.test(password) ? 'valid' : 'invalid');
    document.getElementById('req-common').className = 'req-item ' + (!TOP_100_PASSWORDS.includes(password.toLowerCase()) ? 'valid' : 'invalid');
}

passwordInput.addEventListener('input', () => {
    validatePassword();
    validatePasswordRepeat();
});

function validatePasswordRepeat() {
    if (!isPasswordMethodManual) return true;

    const password = passwordInput.value;
    const passwordRepeat = passwordRepeatInput.value;
    const errorEl = document.getElementById('passwordRepeatError');
    const successEl = document.getElementById('passwordRepeatSuccess');

    if (passwordRepeat.length === 0) {
        errorEl.textContent = '';
        successEl.textContent = '';
        passwordRepeatInput.classList.remove('error', 'success');
        return false;
    }

    if (password !== passwordRepeat) {
        errorEl.textContent = 'Пароли не совпадают';
        successEl.textContent = '';
        passwordRepeatInput.classList.add('error');
        passwordRepeatInput.classList.remove('success');
        return false;
    }

    errorEl.textContent = '';
    successEl.textContent = '✓ Пароли совпадают';
    passwordRepeatInput.classList.remove('error');
    passwordRepeatInput.classList.add('success');
    return true;
}

passwordRepeatInput.addEventListener('input', validatePasswordRepeat);

function generateNickname() {
    const firstName = firstNameInput.value.trim();
    const lastName = lastNameInput.value.trim();

    if (!firstName || !lastName) {
        alert('Сначала введите имя и фамилию');
        return;
    }

    nicknameAttempts++;
    nicknameAttemptsEl.textContent = `Попыток генерации: ${nicknameAttempts}/5`;

    if (nicknameAttempts > 5) {
        nicknameInput.readOnly = false;
        nicknameInput.focus();
        generateNicknameBtn.textContent = '✏️ Редактировать';
        return;
    }

    const firstLetters = firstName.slice(0, Math.floor(Math.random() * 3) + 1).toLowerCase();
    const lastLetters = lastName.slice(0, Math.floor(Math.random() * 3) + 1).toLowerCase();

    const number = Math.floor(Math.random() * 9900) + 100;

    const suffixes = ['_', 'x', 'z', 'pro', 'official', 'real', 'the', 'mr', 'ms', 'dev', 'art', 'design'];
    const suffix = Math.random() > 0.3 ? suffixes[Math.floor(Math.random() * suffixes.length)] : '';

    const nickname = `${firstLetters}${lastLetters}${number}${suffix}`;
    nicknameInput.value = nickname;

    checkNicknameUniqueness(nickname);
}

async function checkNicknameUniqueness(nickname) {
    try {
        const response = await fetch(`${API_BASE_URL}/users`);
        const allUsers = await response.json();

        const errorEl = document.getElementById('nicknameError');
        const successEl = document.getElementById('nicknameSuccess');

        const exists = allUsers.some(user => user.nickname === nickname);

        if (exists) {
            errorEl.textContent = 'Этот никнейм уже занят. Попробуйте сгенерировать другой.';
            successEl.textContent = '';
            nicknameInput.classList.add('error');
            nicknameInput.classList.remove('success');
            return false;
        }

        errorEl.textContent = '';
        successEl.textContent = '✓ Никнейм доступен';
        nicknameInput.classList.remove('error');
        nicknameInput.classList.add('success');
        return true;
    } catch (error) {
        console.error('Ошибка проверки никнейма:', error);
        return true;
    }
}

generateNicknameBtn.addEventListener('click', generateNickname);

nicknameInput.addEventListener('input', () => {
    if (!nicknameInput.readOnly) {
        checkNicknameUniqueness(nicknameInput.value);
    }
});

function validateName(input, errorId) {
    const value = input.value.trim();
    const errorEl = document.getElementById(errorId);

    if (value.length === 0) {
        errorEl.textContent = '';
        input.classList.remove('error', 'success');
        return false;
    }

    if (value.length < 2) {
        errorEl.textContent = 'Минимум 2 символа';
        input.classList.add('error');
        input.classList.remove('success');
        return false;
    }

    if (!/^[а-яА-Яa-zA-Z]+$/.test(value)) {
        errorEl.textContent = 'Только буквы';
        input.classList.add('error');
        input.classList.remove('success');
        return false;
    }

    errorEl.textContent = '';
    input.classList.remove('error');
    input.classList.add('success');
    return true;
}

firstNameInput.addEventListener('input', () => validateName(firstNameInput, 'firstNameError'));
lastNameInput.addEventListener('input', () => validateName(lastNameInput, 'lastNameError'));

function validateAgreement() {
    const errorEl = document.getElementById('agreementError');

    if (!agreementCheckbox.checked) {
        errorEl.textContent = 'Необходимо принять соглашение пользователя';
        return false;
    }

    errorEl.textContent = '';
    return true;
}

agreementCheckbox.addEventListener('change', validateForm);

function validateForm() {
    const isPhoneValid = validatePhone();
    const isEmailValid = validateEmail();
    const isDateValid = validateDateOfBirth();
    const isPasswordValid = isPasswordMethodManual ? validatePassword() && validatePasswordRepeat() : true;
    const isFirstNameValid = validateName(firstNameInput, 'firstNameError');
    const isLastNameValid = validateName(lastNameInput, 'lastNameError');
    const isNicknameValid = nicknameInput.value.length > 0;
    const isAgreementValid = validateAgreement();

    const isValid = isPhoneValid && isEmailValid && isDateValid && isPasswordValid &&
        isFirstNameValid && isLastNameValid && isNicknameValid && isAgreementValid;

    submitBtn.disabled = !isValid;
    return isValid;
}

form.addEventListener('submit', async (e) => {
    e.preventDefault();

    if (!validateForm()) {
        alert('Пожалуйста, исправьте ошибки в форме');
        return;
    }

    const rawPassword = isPasswordMethodManual ? passwordInput.value : autoGeneratedPassword;

    const hashedPassword = await hashPassword(rawPassword);

    const userData = {
        phone: phoneInput.value.replace(/\D/g, ''),
        email: emailInput.value.trim(),
        password: hashedPassword,
        dateOfBirth: dateOfBirthInput.value,
        firstName: firstNameInput.value.trim(),
        lastName: lastNameInput.value.trim(),
        patronymic: patronymicInput.value.trim(),
        nickname: nicknameInput.value.trim(),
        role: 'user',
        agreementAccepted: agreementCheckbox.checked,
        createdAt: new Date().toISOString()
    };

    try {
        const nicknameCheck = await checkNicknameUniqueness(userData.nickname);
        if (!nicknameCheck) {
            alert('Этот никнейм уже занят. Пожалуйста, выберите другой.');
            return;
        }

        const response = await fetch(`${API_BASE_URL}/users`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(userData)
        });

        if (response.ok) {
            const newUser = await response.json();
            const { password, ...safeUser } = newUser;
            localStorage.setItem('currentUser', JSON.stringify(safeUser));

            alert('✅ Регистрация успешна! Добро пожаловать!');
            window.location.href = 'catalog.html';
        } else {
            alert('❌ Ошибка при регистрации. Попробуйте ещё раз.');
        }
    } catch (error) {
        console.error('Ошибка регистрации:', error);
        alert('❌ Произошла ошибка при регистрации');
    }
});

document.addEventListener('DOMContentLoaded', () => {
    const maxDate = new Date();
    maxDate.setFullYear(maxDate.getFullYear() - 16);
    dateOfBirthInput.max = maxDate.toISOString().split('T')[0];

    const minDate = new Date();
    minDate.setFullYear(minDate.getFullYear() - 100);
    dateOfBirthInput.min = minDate.toISOString().split('T')[0];
});
