const programsData = [
    {
        id: 1,
        name: "Коммуникационный дизайн",
        category: "design",
        categoryName: "Дизайн",
        description: "Программа по созданию визуальных коммуникаций и графическому дизайну",
        price: 350000,
        duration: 48,
        durationUnit: "месяцев",
        rating: 4.8,
        image: "images/programs/communication-design.png",
        level: "Бакалавриат",
        language: "Русский"
    },
    {
        id: 2,
        name: "Анимация и иллюстрация",
        category: "art",
        categoryName: "Искусство",
        description: "Создание анимационных фильмов, иллюстраций и визуальных историй",
        price: 320000,
        duration: 48,
        durationUnit: "месяцев",
        rating: 4.9,
        image: "images/programs/animation.jpg",
        level: "Бакалавриат",
        language: "Русский"
    },
    {
        id: 3,
        name: "Гейм-дизайн",
        category: "tech",
        categoryName: "Технологии",
        description: "Проектирование игровых миров, механик и пользовательского опыта в играх",
        price: 380000,
        duration: 48,
        durationUnit: "месяцев",
        rating: 4.7,
        image: "images/programs/game-design.jpg",
        level: "Бакалавриат",
        language: "Русский"
    },
    {
        id: 4,
        name: "Мода",
        category: "design",
        categoryName: "Дизайн",
        description: "Дизайн одежды, создание коллекций и работа с текстилем",
        price: 340000,
        duration: 48,
        durationUnit: "месяцев",
        rating: 4.6,
        image: "images/programs/fashion.jpg",
        level: "Бакалавриат",
        language: "Русский"
    },
    {
        id: 5,
        name: "Современное искусство",
        category: "art",
        categoryName: "Искусство",
        description: "Актуальные художественные практики и кураторство",
        price: 290000,
        duration: 24,
        durationUnit: "месяцев",
        rating: 4.5,
        image: "images/programs/contemporary-art.jpg",
        level: "Магистратура",
        language: "Русский"
    },
    {
        id: 6,
        name: "Дизайн и программирование",
        category: "tech",
        categoryName: "Технологии",
        description: "Создание интерактивных цифровых продуктов и веб-приложений",
        price: 400000,
        duration: 48,
        durationUnit: "месяцев",
        rating: 4.9,
        image: "images/programs/design-code.jpg",
        level: "Бакалавриат",
        language: "Русский"
    },
    {
        id: 7,
        name: "Медиа и дизайн",
        category: "media",
        categoryName: "Медиа",
        description: "Создание мультимедийного контента и цифровых медиапродуктов",
        price: 310000,
        duration: 48,
        durationUnit: "месяцев",
        rating: 4.4,
        image: "images/programs/media-design.png",
        level: "Бакалавриат",
        language: "Русский"
    },
    {
        id: 8,
        name: "Фотография",
        category: "art",
        categoryName: "Искусство",
        description: "Художественная и коммерческая фотография, работа со светом",
        price: 280000,
        duration: 24,
        durationUnit: "месяцев",
        rating: 4.7,
        image: "images/programs/photography.jpg",
        level: "Магистратура",
        language: "Русский"
    },
    {
        id: 9,
        name: "Дизайн среды",
        category: "design",
        categoryName: "Дизайн",
        description: "Проектирование интерьеров, выставочных пространств и средового дизайна",
        price: 330000,
        duration: 48,
        durationUnit: "месяцев",
        rating: 4.6,
        image: "images/programs/environment-design.jpg",
        level: "Бакалавриат",
        language: "Русский"
    },
    {
        id: 10,
        name: "Саунд-арт",
        category: "art",
        categoryName: "Искусство",
        description: "Звуковой дизайн, саунд-арт и экспериментальная музыка",
        price: 270000,
        duration: 24,
        durationUnit: "месяцев",
        rating: 4.3,
        image: "images/programs/sound-art.jpg",
        level: "Магистратура",
        language: "Русский"
    },
    {
        id: 11,
        name: "Типографика и дизайн книги",
        category: "design",
        categoryName: "Дизайн",
        description: "Шрифтовой дизайн, верстка и книжная графика",
        price: 260000,
        duration: 18,
        durationUnit: "месяцев",
        rating: 4.5,
        image: "images/programs/typography.jpg",
        level: "ДПО",
        language: "Русский"
    },
    {
        id: 12,
        name: "Искусство рекламы",
        category: "media",
        categoryName: "Медиа",
        description: "Создание рекламных кампаний и креативных концепций",
        price: 240000,
        duration: 12,
        durationUnit: "месяцев",
        rating: 4.4,
        image: "images/programs/advertising.jpg",
        level: "ДПО",
        language: "Русский"
    },
    {
        id: 13,
        name: "3D-постпродакшн",
        category: "tech",
        categoryName: "Технологии",
        description: "Трехмерная графика, визуальные эффекты и композитинг",
        price: 360000,
        duration: 24,
        durationUnit: "месяцев",
        rating: 4.8,
        image: "images/programs/3d-post.jpg",
        level: "ДПО",
        language: "Русский"
    },
    {
        id: 14,
        name: "Ювелирный дизайн",
        category: "design",
        categoryName: "Дизайн",
        description: "Проектирование и создание ювелирных изделий",
        price: 290000,
        duration: 18,
        durationUnit: "месяцев",
        rating: 4.6,
        image: "images/programs/jewelry.jpg",
        level: "ДПО",
        language: "Русский"
    },
    {
        id: 15,
        name: "Менеджмент креативных проектов",
        category: "media",
        categoryName: "Медиа",
        description: "Менеджмент креативных проектов и культурных институций",
        price: 320000,
        duration: 24,
        durationUnit: "месяцев",
        rating: 4.7,
        image: "images/programs/creative-management.jpg",
        level: "Магистратура",
        language: "Русский"
    }
];
